import type { DigestStats } from "../shared/computeDigestStats";
import { formatDigestDate, type IssueWriter } from "./postWeeklyDigest";

const ORG_SUMMARY_REPO = ".github";

export interface RepoReport {
  repository: string;
  stats: DigestStats;
}

export interface OrgSummaryTotals extends DigestStats {
  cleanRepos: number;
  reposNeedingAttention: number;
}

/**
 * Computes aggregated summary metrics across all repository reports in an organization.
 */
export function computeOrgTotals(reports: RepoReport[]): OrgSummaryTotals {
  let patchable = 0;
  let needsReview = 0;
  let acceptedRisk = 0;
  let total = 0;
  let cleanRepos = 0;
  let reposNeedingAttention = 0;

  for (const r of reports) {
    patchable += r.stats.patchable;
    needsReview += r.stats.needsReview;
    acceptedRisk += r.stats.acceptedRisk;
    total += r.stats.total;

    const open = r.stats.patchable + r.stats.needsReview;
    if (open === 0) {
      cleanRepos++;
    } else {
      reposNeedingAttention++;
    }
  }

  return {
    patchable,
    needsReview,
    acceptedRisk,
    total,
    cleanRepos,
    reposNeedingAttention,
  };
}

/**
 * Builds the markdown report body for an organization-wide security summary.
 */
export function buildOrgSummaryBody(
  orgName: string,
  reports: RepoReport[],
  date: Date = new Date(),
): string {
  const totals = computeOrgTotals(reports);
  const formattedDate = formatDigestDate(date);

  const statusBanner =
    totals.reposNeedingAttention === 0
      ? `✅ **All ${reports.length} monitored repositories are clean** — no open vulnerabilities.`
      : `⚠️ **${totals.reposNeedingAttention} of ${reports.length} repositories** have open findings requiring attention.`;

  const rows = reports.map((r) => {
    const open = r.stats.patchable + r.stats.needsReview;
    const health = open === 0 ? "✅ Clean" : `⚠️ ${open} open`;
    return `| \`${r.repository}\` | ${r.stats.patchable} | ${r.stats.needsReview} | ${r.stats.acceptedRisk} | ${r.stats.total} | ${health} |`;
  });

  return [
    `## 🔒 RiskLedger Organization Security Summary — ${formattedDate}`,
    "",
    `Organization: **${orgName}**`,
    "",
    statusBanner,
    "",
    "| Repository | 🔧 Auto-patchable | 👀 Needs Review | ✅ Accepted Risk | 📦 Total | Health |",
    "| ---------- | ----------------- | --------------- | ---------------- | -------- | ------ |",
    ...rows,
    `| **Total (${reports.length} repos)** | **${totals.patchable}** | **${totals.needsReview}** | **${totals.acceptedRisk}** | **${totals.total}** | **${totals.reposNeedingAttention === 0 ? "✅ Clean" : "⚠️ Needs Action"}** |`,
    "",
    "---",
    "_Generated by [RiskLedger](https://github.com/apps/riskledger). Run `/recheck` in any open PR/issue to re-evaluate policy._",
  ].join("\n");
}

/**
 * Posts an organization-wide security summary issue to the organization's central `.github` repository.
 */
export async function postOrgSummary(
  issues: IssueWriter,
  owner: string,
  reports: RepoReport[],
  date: Date = new Date(),
): Promise<void> {
  const formattedDate = formatDigestDate(date);

  await issues.create({
    owner,
    repo: ORG_SUMMARY_REPO,
    title: `🔒 RiskLedger Organization Security Summary — ${formattedDate}`,
    body: buildOrgSummaryBody(owner, reports, date),
    labels: ["security"],
  });
}
