import type { DigestStats } from "../shared/computeDigestStats";
import type { RepositoryRef } from "./openPatchPR";

export interface IssueWriter {
  create: (input: {
    owner: string;
    repo: string;
    title: string;
    body: string;
    labels?: string[];
  }) => Promise<unknown>;
}

/**
 * Formats a UTC date as "YYYY-MM-DD" for use in digest issue titles.
 */
export function formatDigestDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/**
 * Builds the markdown body for a weekly digest GitHub issue.
 */
export function buildDigestBody(stats: DigestStats, date: Date): string {
  const open = stats.patchable + stats.needsReview;
  const statusLine =
    open === 0
      ? "✅ No open vulnerabilities — repository is clean."
      : `⚠️ **${open} open** finding${open === 1 ? "" : "s"} require${open === 1 ? "s" : ""} attention.`;

  return [
    `## RiskLedger Security Digest — ${formatDigestDate(date)}`,
    "",
    statusLine,
    "",
    "| Category | Count |",
    "| -------- | ----- |",
    `| 🔧 Auto-patchable | ${stats.patchable} |`,
    `| 👀 Needs review | ${stats.needsReview} |`,
    `| ✅ Accepted risk | ${stats.acceptedRisk} |`,
    `| 📦 Total findings | ${stats.total} |`,
    "",
    "---",
    "_Generated by [RiskLedger](https://github.com/apps/riskledger). " +
      "Reply `/recheck` on any open finding to re-run classification._",
  ].join("\n");
}

/**
 * Posts a weekly security digest as a GitHub issue on the target repository.
 */
export async function postWeeklyDigest(
  issues: IssueWriter,
  repository: RepositoryRef,
  stats: DigestStats,
  date: Date = new Date(),
): Promise<void> {
  await issues.create({
    owner: repository.owner,
    repo: repository.repo,
    title: `🔒 RiskLedger Weekly Security Digest — ${formatDigestDate(date)}`,
    body: buildDigestBody(stats, date),
    labels: ["security"],
  });
}
